# Generated by Django 4.1.3 on 2022-11-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_name_alter_event_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organizer_id',
        ),
    ]
