# Generated by Django 4.1.3 on 2022-11-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_organizer_event_organizer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
