# Generated by Django 4.1.3 on 2022-11-11 23:01

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_address_remove_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.JSONField(blank=True, default=events.models.place_default),
        ),
    ]
