# Generated by Django 4.1.3 on 2022-11-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rompgroup_members'),
        ('events', '0007_attendance_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='romp_group', to='accounts.rompgroup'),
        ),
    ]
