# Generated by Django 4.1.3 on 2022-11-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rompgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='rompgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
