# Generated by Django 4.1.3 on 2022-11-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_following_alter_followers_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follows', to='accounts.profile'),
        ),
    ]
