# Generated by Django 4.1.3 on 2022-11-07 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rompgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rompgroup',
            name='users',
        ),
    ]
