# Generated by Django 4.1.3 on 2022-11-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userfollowers_user_alter_userfollowing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='profile_followers', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='UserFollowers',
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
