# Generated by Django 4.1.3 on 2022-11-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
